export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'

export const SLIDER_SET_IS_MOVING = 'SLIDER_SET_MOVING'
export const SLIDER_SET_CURRENT_PROJECT_ID = 'SLIDER_SET_CURRENT_PROJECT_ID'